#!/usr/bin/env python3
# pylint: disable=too-few-public-methods,invalid-name,missing-docstring,bad-whitespace

STUDENT_PAYLOAD = {
    "bioStudent": "string",
    "bloodGroup": "AB +ve",
    "disability": "No",
    "emergencyContactNo": "+918902693965",
    "schoolTransport": "Yes",
    "flatNo": "215",
    "streetName": "Wall Street",
    "locality": "Superb",
    "landmark": "Modi Mahal",
    "city": "New Delhi",
    "state": "Delhi",
    "country": "India",
    "pin": "110044",
    "fatherFirstName": "Leonardo",
    "fatherMiddleName": "Di",
    "fatherLastName": "Caprio",
    "fatherOccupation": "Acting",
    "fatherHighestDegree": "10th",
    "fatherContactNo": "+919999999999",
    "fatherEmailId": "father@email.com",
    "motherFirstName": "Anjelina",
    "motherMiddleName": "Of",
    "motherLastName": "Hollywood",
    "motherOccupation": "Acting",
    "motherHighestDegree": "12th",
    "motherContactNo": "+919999999999",
    "motherEmailId": "mother@email.com",
    "guardianFirstName": "Guardian",
    "guardianMiddleName": "Of",
    "guardianLastName": "Galaxy",
    "guardianOccupation": "Acting",
    "guardianHighestDegree": "8th",
    "guardianContactNo": "+919999999999",
    "guardianEmailId": "guardian@email.com",
    "staffChild": "No"
}


EMPLOYEE_PAYLOAD = {
    "bioEmployee": "string",
    "bloodGroup": "AB +ve",
    "disability": "No",
    "qualification": "B.Ed.",
    "emergencyContactNo": "+918902693965",
    "schoolTransport": "Yes/No",
    "flatNo": "215",
    "streetName": "Wall Street",
    "locality": "Superb",
    "landmark": "Modi Mahal",
    "city": "New Delhi",
    "state": "Delhi",
    "country": "India",
    "pin": "110044",
    "fatherFirstName": "Leonardo",
    "fatherMiddleName": "Di",
    "fatherLastName": "Caprio",
    "fatherOccupation": "Acting",
    "fatherHighestDegree": "10th",
    "fatherContactNo": "+919999999999",
    "fatherEmailId": "father@email.com",
    "motherFirstName": "Anjelina",
    "motherMiddleName": "Of",
    "motherLastName": "Hollywood",
    "motherOccupation": "Acting",
    "motherHighestDegree": "12th",
    "motherContactNo": "+919999999999",
    "motherEmailId": "mother@email.com"
}
